### ISSUE TITLE
macOS Sequoia - after Shutdown, it generated Kernel Panic, freeze and don't shutdown

### ISSUE THREAD

**Issue by luchina-gabriel** [SongXiaoXi/AppleIGC#12]
Hi,

I installed macOS Sequoia (first Beta) and noticed that when shutting down or restarting macOS, it generates Kernel Panic.

![KP-Shutdown-AppleIGC-I226](https://github.com/SongXiaoXi/AppleIGC/assets/23700365/cf001588-c070-4bf7-a809-4defa1305746)

The rest of the network card's operation appears to be ok.

**Comment by SongXiaoXi** [comment]
Can you provide a full panic log? It may appear in a window that says 'Your computer was restarted because of a problem' after the next boot, or it may be located at `/Library/Logs/DiagnosticReports`.

**Comment by luchina-gabriel** [comment]
Of course @SongXiaoXi , however I removed Sequoia, I will install it again, generate the logs and send them to you shortly. Thanks

**Comment by luchina-gabriel** [comment]
Hi @SongXiaoXi ,

Here are the files (I already generated the spindump).

[log-files.zip](https://github.com/user-attachments/files/15828365/log-files.zip)

Thanks ;)

**Comment by SongXiaoXi** [comment]
Hi, could you please test the following temporary build?
[AppleIGC.kext.zip](https://github.com/user-attachments/files/15834354/AppleIGC.kext.zip)

**Comment by luchina-gabriel** [comment]
Hi @SongXiaoXi ,

Worked perfectly.

I tested both on macOS Sequoia, which was where the problem I reported was occurring, and also on Sonoma 14.5, both apparently 100%.

Thank you very much :)
