### ISSUE TITLE
Bridging an Ethernet card under a VirtualBox virtual machine may be problematic (在VirtualBox虚拟机下桥接以太网卡可能会有问题)

### ISSUE THREAD

**Issue by qiutuleng** [SongXiaoXi/AppleIGC#2]
Description:
I am creating a Linux virtual machine with VirtualBox, choosing Bridge for NIC mode and Ethernet card for the target NIC, and then booting the virtual machine will fail.

Error content:
VirtualBOX: vmnet_start_interface returned 1001 (VERR_INVALID_PARAMETER).

Try:
1. Wi-Fi NIC using White Apple NIC BCM94360CD, it can boot normally.
2. Use AppleIntelI210Ethernet.kext to drive the Ethernet card, it can boot normally.

Motherboard: Gigabyte Z490 Aorus Pro AX
NIC: I225-V

------------------------------------------------------------------------------------------
描述：
我是用VirtualBox创建了Linux虚拟机，网卡模式选择桥接，目标网卡选择以太网卡，然后启动虚拟机会失败。

错误内容：
VirtualBOX: vmnet_start_interface returned 1001 (VERR_INVALID_PARAMETER).

尝试：
1. Wi-Fi网卡使用白苹果网卡BCM94360CD，能正常启动。
2. 使用AppleIntelI210Ethernet.kext来驱动以太网卡，能正常启动。

主板：Gigabyte Z490 Aorus Pro AX
网卡：I225-V

**Comment by SongXiaoXi** [comment]
我之前测试用的Parallels Desktop，在/Library/Preferences/Parallels/network.desktop.xml中设置了UseKextless = 0,bridge模式可以正常使用。不知道VirtualBox有没有类似的设置选项。vmnet是苹果自己的虚拟网卡API，考虑到kext API已经废弃，估计是我没实现哪个私有API，等我有时间看看。

The Parallels Desktop I used for testing earlier had the UseKextless = 0 setting in /Library/Preferences/Parallels/network.desktop.xml, which allowed bridge mode to function properly. I'm not sure if VirtualBox has a similar setting option. vmnet is Apple's own virtual network card API, and considering that the kext API has been deprecated, it's likely that I haven't implemented some private API. I'll take a look when I have some time.

**Comment by qiutuleng** [comment]
目前看起来一切正常，获取的IP也能通过局域网内的其他设备访问。

非常感谢您的贡献。

<img width="2076" alt="CleanShot 2023-05-05 at 10 58 06@2x" src="https://user-images.githubusercontent.com/30284139/236369143-34516dd2-3491-424f-aa95-b882885734a6.png">
